name: CI & trigger Render deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'maven'

      - name: Build & test
        run: mvn -B clean verify

  trigger-render:
    needs: ci
    runs-on: ubuntu-latest
    if: ${{ needs.ci.result == 'success' }}
    steps:
      - name: Validate deploy hook secret
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            echo "RENDER_DEPLOY_HOOK_URL is not set in repo secrets."
            exit 1
          fi

      - name: Trigger Render deploy (Deploy Hook)
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          # Optional: show masked host for debugging
          echo "Triggering Render deploy..."
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_URL"
          echo "Deploy hook triggered."
